#!/usr/bin/env bash

set -euo pipefail

# Bundle the current local OpenClaw build together with a minimal runtime
# profile so the target Mac installs THIS repository version instead of
# upstream openclaw@latest.

OPENCLAW_HOME="${OPENCLAW_HOME:-$HOME/.openclaw}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ARTIFACTS_ROOT="${OPENCLAW_MAC_BUNDLE_OUTPUT_DIR:-${REPO_ROOT}/.artifacts/openclaw-mac-bundles}"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
OUT_BASENAME="openclaw-mac-bundle-${TIMESTAMP}"
OUT_DIR="${ARTIFACTS_ROOT}/${OUT_BASENAME}"
OUT_TAR="${ARTIFACTS_ROOT}/${OUT_BASENAME}.tar.gz"
PACKAGE_DIR="${OUT_DIR}/packages"
LOCAL_PACKAGE_TGZ=""
LOCAL_PACKAGE_PATH=""
BUNDLE_ENV_PATH="${OUT_DIR}/.openclaw/.env"

echo "Packing OpenClaw runtime profile from: ${OPENCLAW_HOME}"
echo "Using local repository: ${REPO_ROOT}"
echo "Writing bundle artifacts to: ${ARTIFACTS_ROOT}"

mkdir -p "${ARTIFACTS_ROOT}"
mkdir -p "${OUT_DIR}/.openclaw"
mkdir -p "${PACKAGE_DIR}"

copy_if_exists() {
  local src="$1"
  local dst="$2"
  if [ -f "${src}" ]; then
    mkdir -p "$(dirname "${dst}")"
    cp "${src}" "${dst}"
    echo "  [profile] ${src} -> ${dst}"
  else
    echo "  [profile] skipped missing file: ${src}"
  fi
}

dotenv_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  printf '"%s"' "${value}"
}

read_existing_bridge_token() {
  local source_env="$1"
  [ -f "${source_env}" ] || return 1

  python3 - "${source_env}" <<'PY'
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
matches = re.findall(r'^[ \t]*OPENCLAW_BRIDGE_TOKEN[ \t]*=[ \t]*(.+)[ \t]*$', text, re.MULTILINE)
if not matches:
    raise SystemExit(1)
value = matches[-1].strip()
if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
    value = value[1:-1]
print(value)
PY
}

create_bundle_env() {
  local dst="$1"
  local source_env="${OPENCLAW_HOME}/.env"
  local generated_bridge_token="${OPENCLAW_BRIDGE_TOKEN:-}"

  if [ -z "${generated_bridge_token}" ]; then
    generated_bridge_token="$(read_existing_bridge_token "${source_env}" 2>/dev/null || true)"
  fi
  if [ -z "${generated_bridge_token}" ]; then
    generated_bridge_token="change-me"
  fi

  cat > "${dst}" <<EOF
# Generated by scripts/package-openclaw-mac.sh
OPENCLAW_BRIDGE_TOKEN=$(dotenv_quote "${generated_bridge_token}")
EOF
  echo "  [profile] generated minimal env: ${dst}"

  cat >> "${dst}" <<'EOF'
OPENCLAW_CONTROL_PLANE_STATE_FILE="__OPENCLAW_HOME__/control-plane-state.json"
EOF
}

echo
echo "Building and packing local OpenClaw package..."
pushd "${REPO_ROOT}" >/dev/null
LOCAL_PACKAGE_TGZ="$(pnpm pack --pack-destination "${PACKAGE_DIR}" | tail -n 1 | tr -d '\r')"
popd >/dev/null

if [ -z "${LOCAL_PACKAGE_TGZ}" ]; then
  echo "Failed to produce local OpenClaw tarball" >&2
  exit 1
fi

if [[ "${LOCAL_PACKAGE_TGZ}" = /* ]]; then
  LOCAL_PACKAGE_PATH="${LOCAL_PACKAGE_TGZ}"
  LOCAL_PACKAGE_TGZ="$(basename "${LOCAL_PACKAGE_PATH}")"
else
  LOCAL_PACKAGE_PATH="${PACKAGE_DIR}/${LOCAL_PACKAGE_TGZ}"
fi

if [ ! -f "${LOCAL_PACKAGE_PATH}" ]; then
  echo "Failed to produce local OpenClaw tarball" >&2
  exit 1
fi

echo "  [package] ${LOCAL_PACKAGE_PATH}"

copy_if_exists "${OPENCLAW_HOME}/openclaw.json" "${OUT_DIR}/.openclaw/openclaw.json"
copy_if_exists "${OPENCLAW_HOME}/exec-approvals.json" "${OUT_DIR}/.openclaw/exec-approvals.json"
copy_if_exists "${OPENCLAW_HOME}/workspace/SOUL.md" "${OUT_DIR}/.openclaw/workspace/SOUL.md"
create_bundle_env "${BUNDLE_ENV_PATH}"

cat > "${OUT_DIR}/README-import.md" <<EOF
OpenClaw macOS runtime bundle
=============================

This bundle contains:

- packages/${LOCAL_PACKAGE_TGZ}
- .openclaw/.env
- .openclaw/openclaw.json
- .openclaw/exec-approvals.json
- .openclaw/workspace/SOUL.md

Important:

- Install the packaged local OpenClaw tarball from this bundle.
- Do NOT use \`npm install -g openclaw@latest\` on the target Mac, because the
  upstream package does not include the control-plane compatibility layer used
  by agent-bot-task-a.

To import on a target Mac:

1. Ensure Node.js (22.16+ or 24.x) is installed.

2. Extract this archive in your home directory:

   cd ~
   tar -xzf /path/to/${OUT_TAR}

3. Install THIS local OpenClaw build globally:

   npm install -g ~/${OUT_BASENAME}/packages/${LOCAL_PACKAGE_TGZ}

4. Restore the runtime profile:

   mkdir -p ~/.openclaw/workspace
   sed "s#__OPENCLAW_HOME__#\$HOME/.openclaw#g" ~/${OUT_BASENAME}/.openclaw/.env > ~/.openclaw/.env
   cp ~/${OUT_BASENAME}/.openclaw/openclaw.json ~/.openclaw/openclaw.json
   cp ~/${OUT_BASENAME}/.openclaw/exec-approvals.json ~/.openclaw/exec-approvals.json
   cp ~/${OUT_BASENAME}/.openclaw/workspace/SOUL.md ~/.openclaw/workspace/SOUL.md

5. Choose how you want to run the Gateway:

   Foreground (one-shot terminal run):

   export OPENCLAW_BRIDGE_TOKEN=change-me
   export OPENCLAW_CONTROL_PLANE_STATE_FILE="\$HOME/.openclaw/control-plane-state.json"
   openclaw gateway run --config ~/.openclaw/openclaw.json

   launchd service (so \`openclaw gateway start\` works later):

   # ~/.openclaw/.env has already been restored above; edit it if needed.
   openclaw gateway install
   openclaw gateway status --deep

6. Verify the compatibility routes:

   curl -i http://127.0.0.1:15661/__control-plane/runtime-context \\
     -H "x-openclaw-bridge-token: \$OPENCLAW_BRIDGE_TOKEN"

   curl -i -X POST http://127.0.0.1:15661/__control-plane/bootstrap \\
     -H "content-type: application/json" \\
     -H "x-openclaw-bridge-token: \$OPENCLAW_BRIDGE_TOKEN" \\
     -d '{}'

   curl -i -X POST http://127.0.0.1:15661/__control-plane/skills/snapshot/apply \\
     -H "content-type: application/json" \\
     -H "x-openclaw-bridge-token: \$OPENCLAW_BRIDGE_TOKEN" \\
     -d '{"snapshotId":"debug","packages":[]}'

Expected:

- runtime-context returns 200
- bootstrap no longer returns 404
- skills/snapshot/apply no longer returns 404
EOF

cat > "${OUT_DIR}/install-local-openclaw.sh" <<EOF
#!/usr/bin/env bash

set -euo pipefail

BUNDLE_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
PACKAGE_NAME="${LOCAL_PACKAGE_TGZ}"

mkdir -p "\$HOME/.openclaw/workspace"
npm install -g "\${BUNDLE_DIR}/packages/\${PACKAGE_NAME}"

if [ -f "\${BUNDLE_DIR}/.openclaw/openclaw.json" ]; then
  cp "\${BUNDLE_DIR}/.openclaw/openclaw.json" "\$HOME/.openclaw/openclaw.json"
fi
if [ -f "\${BUNDLE_DIR}/.openclaw/exec-approvals.json" ]; then
  cp "\${BUNDLE_DIR}/.openclaw/exec-approvals.json" "\$HOME/.openclaw/exec-approvals.json"
fi
if [ -f "\${BUNDLE_DIR}/.openclaw/workspace/SOUL.md" ]; then
  mkdir -p "\$HOME/.openclaw/workspace"
  cp "\${BUNDLE_DIR}/.openclaw/workspace/SOUL.md" "\$HOME/.openclaw/workspace/SOUL.md"
fi
if [ -f "\${BUNDLE_DIR}/.openclaw/.env" ]; then
  BUNDLE_ENV_CONTENT="\$(<"\${BUNDLE_DIR}/.openclaw/.env")"
  BUNDLE_ENV_CONTENT="\${BUNDLE_ENV_CONTENT//__OPENCLAW_HOME__/\$HOME/.openclaw}"
  printf '%s\n' "\${BUNDLE_ENV_CONTENT}" > "\$HOME/.openclaw/.env"
fi

echo "Installed local OpenClaw package: \${PACKAGE_NAME}"
echo "Next:"
echo "  Foreground run:"
echo "    export OPENCLAW_BRIDGE_TOKEN=<same token as control plane>"
echo "    export OPENCLAW_CONTROL_PLANE_STATE_FILE=\$HOME/.openclaw/control-plane-state.json"
echo "    openclaw gateway run --config ~/.openclaw/openclaw.json"
echo "  launchd service:"
echo "    # .env was restored to \$HOME/.openclaw/.env"
echo "    openclaw gateway install"
echo "    openclaw gateway status --deep"
EOF

chmod +x "${OUT_DIR}/install-local-openclaw.sh"

echo "Creating archive: ${OUT_TAR}"
tar -czf "${OUT_TAR}" -C "${ARTIFACTS_ROOT}" "${OUT_BASENAME}"

echo
echo "Done."
echo "Bundle path:"
echo "  ${OUT_TAR}"
echo
echo "Copy this archive to the target Mac, extract it, then follow README-import.md."
